---
- name: Hello World!
  sudo: yes
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    
  - name: Creates directory
    file:
       path: /opt/ansibletower
       state: directory
